### ISSUE TITLE
Support for metrics history

### ISSUE THREAD

**Issue by hoducha** [mikaelvesavuori/dorametrix#10]
**Is your feature request related to a problem? Please describe.**
Currently, the API only returns the average metric value for a period of time [DynamoDbRepo.ts#L47](https://github.com/mikaelvesavuori/dorametrix/blob/905a29f7ab59684a544c2eab4b9ba036406cb377/src/repositories/DynamoDbRepo.ts#L47). It would be great if it can return the metric history so the client can visualize history data as a chart similar to [fourkeys](https://github.com/GoogleCloudPlatform/fourkeys).

**Describe the solution you'd like**
As the history data is immutable, it can be pre-calculated and stored in DynamoDB.

**Describe alternatives you've considered**
Currently, we use an in-memory caching strategy [DynamoDbRepo.ts#L26](https://github.com/mikaelvesavuori/dorametrix/blob/905a29f7ab59684a544c2eab4b9ba036406cb377/src/repositories/DynamoDbRepo.ts#L26) which stick to Lambda lifecycle. Should we also consider using DynamoDB as the cache for the metrics?

**Comment by mikaelvesavuori** [comment]
Hey @hoducha! This is a good idea. I don't have bandwidth to actively look into this right now, but I will keep this open. Do make a PR if you have a solution proposal in mind.

For your last question, yes, I think that makes sense. The beauty of such a solution is that we get a very read-optimized, cheap, and serverless model compared to e.g. Four Keys.

**Comment by hoducha** [comment]
Thanks @mikaelvesavuori. I like the way you architect the `dorametrix` as a serverless web service. Let me play with the code a bit and see if I can open a PR for this.

**Comment by mikaelvesavuori** [comment]
Hi again! I have been busy with a lot of stuff, including a spiritual cousin called Gitmetrix. Gitmetrix has support for historical metrics. Please check this out to comment on the approach taken and I can look at adjusting Dorametrix to behave similarly. https://github.com/mikaelvesavuori/gitmetrix

**Comment by mikaelvesavuori** [comment]
Just writing to inform that version 2.0 should be out very soon. Please see work at https://github.com/mikaelvesavuori/dorametrix/tree/feature/v2

**Comment by mikaelvesavuori** [comment]
Hi again @hoducha!

Version `2.0.0` is now out with metrics history support: https://github.com/mikaelvesavuori/dorametrix/releases/tag/v2.0.0

I will close this as a result.

Thanks for pitching in!
