### ISSUE TITLE
Contribution code coverage broken

### ISSUE THREAD

**Issue by jprosenbaum** [mikaelvesavuori/dorametrix#24]
Submitting code coverage results fails on attempting to contribute back the repo

https://github.com/mikaelvesavuori/dorametrix/actions/runs/4450039396/jobs/7832573241

`Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag`

**Comment by mikaelvesavuori** [comment]
Yeah I wouldn't care too much about that, it's GitHub trying to stay safe/secure and not share secrets with contributors. Don't worry about that. Will check your PR now by the way.
