### ISSUE TITLE
Metrics not returning correct data

### ISSUE THREAD

**Issue by ghost** [mikaelvesavuori/dorametrix#27]
**Describe the bug**
I've got two fresh deployments of dorametrix (following the documented setup guide) each with a few days old change events and deployment events in the DynamoDB table and the metrics endpoint is always returning 0 changes and 0 deployments for this and other repos. The last deployment endpoint does return the correct data and I've had no issues with POSTing data to dorametrix. Is there something I might be missing in my deployments? I've tried both getting data from two different dates and with the sliding window set. I do see the cached item added to the table after the request.

Anything I'm missing (or more details needed) or is this a known issue?

**Comment by ghost** [comment]
We believe the issue is here https://github.com/mikaelvesavuori/dorametrix/blob/d4eca999ce703c655846a5539a242826da07a522/src/infrastructure/repositories/DynamoDbRepository.ts#L230 where it ends up checking date = date instead of a range of dates. Is that a bug or something intentional and we're missing something?

**Comment by mikaelvesavuori** [comment]
Hi @jfitch11! Something seems to be up with GitHub notifications so I completely missed the issue. Will look into this soon.

**Comment by mikaelvesavuori** [comment]
Hey again @jfitch11. Your assessment was correct. For the life of me, I can't understand how I let that bug creep in... But now it's solved. The solution was to use `>=` for the `sk`.

The solution is pushed, together with some other (minor) fixes, in `3.0.1`. Please see https://github.com/mikaelvesavuori/dorametrix/releases/tag/v3.0.1 for more.
